### ISSUE TITLE
Compound App - REP/WBTC interest earned bug

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-react-apps#10]
@francovenica commented on [Thu Apr 30 2020](https://github.com/gnosis/safe-react/issues/848)

In mainnet https://safe-team-mainnet.staging.gnosisdev.com/app/

Whenever you locked or withdraw REP or WBTC for a few mins you will see the interest earned adding or subtracting the amount being locked or withdrawn respectively. 
This lasts for a few mins and it then goes back to normal

---

@rmeissner commented on [Thu Apr 30 2020](https://github.com/gnosis/safe-react/issues/848#issuecomment-621738855)

I will move this issue to another repo

**Comment by nicosampler** [comment]
@rmeissner this could be related to the time the subgraph needs to process new events. Is it ok for this case to hide balance when is negative?

**Comment by tschubotz** [comment]
I can't seem to reproduce this one either. Is it the same like gnosis/safe-react-apps#11? @francovenica does this issue still exist for you?

**Comment by tschubotz** [comment]
Closing this one for now. Please reopen in case it still exists @francovenica
