### ISSUE TITLE
[Transaction Builder] Constructor is rendered as receive

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-react-apps#109]
When interacting with the Safe proxy (e.g. use the address of the Safe as the target in the builder) a `receive` method is shown with a parameter `_masterCopy`. 

There are 2 issues with that:
1. The real method would be the `constructor` (looking at the ABI response from etherscan), which is not interactable on deployed contracts.
2. The `receive` method cannot have any parameter and can only receive ETH

**Comment by liliya-soroka** [comment]
May be useful for how to check :
1. Use mastercopy address to check "receiver" method
2. use https://gitlab.gnosisdev.com/wallets/gnosis-safe-qa/-/wikis/ABI/ABI-with-payable-function ABI with payable method to check "receiver" method
3.  on rinkeby : use contract address "0x6d7f0754ffeb405d23c51ce938289d4835be3b14" or any ather contract address with valid ABI and with payable methods
