### ISSUE TITLE
App compound - DAI in mainnet

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-react-apps#11]
@francovenica commented on [Thu Apr 30 2020](https://github.com/gnosis/safe-react/issues/847)

In mainnet, whenever you withdrawn locked DAI from the app compound the "Interest earned" balance is reduced by the amount withdrawn.

URL with the safe: https://safe-team-mainnet.staging.gnosisdev.com/app/#/safes/0xB7526726EE1031AF7d700B0351EE5a20dd910177/apps
(who ever check this ask Franco Venica, to make you owner of the safe)

![image.png](https://images.zenhubusercontent.com/5e14b8e3edee21d6f9aa6c8a/9d60bf9a-be6a-4e90-8eb2-762d5f42e6dc)

The etherscan URL of the tx
https://etherscan.io/tx/0xd5a5f47bb655646fdf84168df529d0290e6440a1631d3f65a98d7a6024db6fbe

**Comment by tschubotz** [comment]
I can't seem to reproduce this issue with my Safe. @francovenica  does it still exist for you? If yes, could you please add me as owner of that Safe, pls? `0x8ed44000983B5789798B43AF9d8d9C1e1e2093D0` (mainnet)

**Comment by tschubotz** [comment]
Closing this for now @francovenica  please reopen in case it still persists.
