### ISSUE TITLE
Compound app UI - The buttons are too big and close toguether

### ISSUE THREAD

**Issue by francovenica** [gnosis/safe-react-apps#119]
Original ticket:
https://app.zenhub.com/workspaces/safe-multisig---web-5ce554debb310a35b2f8b6f8/issues/gnosis/safe-react/1580

Env: https://pr1937--safereact.review.gnosisdev.com/rinkeby/app/

Snapshot with the issue and how it should look
![image.png](https://images.zenhubusercontent.com/5e14b8e3edee21d6f9aa6c8a/876ebcd3-e1c3-4915-824f-48ac36d8d981)

**Comment by tschubotz** [comment]
The compound app is super bare bone. I think it's not worth it to spend any effort to fix the UI at this point :)
