### ISSUE TITLE
[Transaction builder]App Crash on decoded data opening after transaction builder refactoring

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-react-apps#123]
### Title/Description
The app is crashed when the decoded data is opened in case of a few transfers to the EOA in the transaction builder transaction
### Environment
Environment: development

**Steps:** 
1. add a transaction by sending ETH to one OEA
2. add a transaction with sending ETH to the second EOA
3. click send transaction
4. click confirm
5. open detail( decoded data) for any of the contract interaction before the txs submitting
Current result: the app is crashed
Expected result: It should be possible to see details of each tx included in the multisend tx

related to the refactoring in the https://github.com/gnosis/safe-react-apps/pull/115

**Comment by nicosampler** [comment]
@liliya-soroka let's move this ticket to the safe-react repository as the fix for it should be handled in that repo.

**Comment by nicosampler** [comment]
The same bug was reported here: https://app.zenhub.com/workspaces/safe-multisig---web-5ce554debb310a35b2f8b6f8/issues/gnosis/safe-react/2205
