### ISSUE TITLE
[WalletConnect] Add BSC support

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-react-apps#127]
Currently it is not possible to use the Wallet Connect app on BSC as it is not using the correct chainid.

![image](https://user-images.githubusercontent.com/2896048/117422849-5aac7d00-af20-11eb-8577-d1da09406e73.png)

Possible solution:
- Adjust https://github.com/gnosis/safe-react-apps/blob/development/apps/wallet-connect/src/utils/networks.ts to include BSC
- Fallback to loading chainid via an rpc call through the interface.

**Comment by mikheevm** [comment]
@rmeissner currently it's not possible because the mapping depends on what string the interface returns as a network name ("binance" and "bsc" are two different networks in the current implementation). Binance's interface uses "Mainnet" as a string but it's already taken. We need to proceed with https://github.com/gnosis/safe-apps-sdk/issues/112 to fix the issue completely.

In the meantime I will deploy a separate WC app instance to be used with bsc

**Comment by winlambo** [comment]
Hi and thank you for all you've done! 

While trying to connect my gnosis-safe on BSC to WalletConnect. I tried using the ETH Mainnet version hosted [here](https://cloudflare-ipfs.com/ipfs/QmX9B982ZAaBzbm6yBoZUS3uLgcizYA6wW65RCXVRZkG6f/) but ran into the network issue.

Would love to know when the BSC hosted version goes live! And wouldn't mind helping in testing when it does.

**Comment by tschubotz** [comment]
This might be solvable easily with an update of the Safe apps SDK
https://github.com/gnosis/safe-apps-sdk/pull/162
https://github.com/gnosis/safe-react/pull/2288

**Comment by tschubotz** [comment]
@winlambo we plan to release BSC support in ~1month. More details here: https://blog.gnosis.pm/gnosis-safes-multichain-future-b676b5b8f431

**Comment by liliya-soroka** [comment]
@francovenica , @katspaugh , @dasanra  I have tried to use the WalletConnect app +  https://bscscan.com/address/0x5A5922E9ef11157498Fa5325bc39E7a1Ba8c402D#writeContract. It works for me for the WC added as a custom app ( using WC link from the PR), but it doesn't work with the WC activated for the BSC chain in our admin panel. We will need to make sure that the correct walletconnect app version is added to the admin pannel
