### ISSUE TITLE
[WalletConnect] Add Polygon support

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-react-apps#128]
# Context

Currently, the WalletConnect Safe app doesn't support dapps on Polygon such as https://app.aave.com/.

# Task

Please add support for Polygon. See #127 for how this was done for BSC.

# Misc

Some technical infos on Polygon [here](https://docs.google.com/document/d/1PyOUWxDCZn9-ulHsV_bT9zRMTiGe9TnERmVLjIlK_OY/edit#).

**Comment by katspaugh** [comment]
Estimation: 5

**Comment by tschubotz** [comment]
This might be solvable easily with an update of the Safe apps SDK
https://github.com/gnosis/safe-apps-sdk/pull/162
https://github.com/gnosis/safe-react/pull/2288
