### ISSUE TITLE
Transaction builder does not update target address correctly

### ISSUE THREAD

**Issue by Arachnid** [gnosis/safe-react-apps#130]
### Title/Description
When using the transaction builder, pasting in a new address for a second transaction updates the ABI, but leaves the original address in the 'to' field. If not caught, this results in sending transactions to the wrong address.

### Steps to reproduce
1. Go to the "Transaction Builder" app.
2. Create a call to contract A.
3. Enter a new address in the first text field for contract B. The app loads the ABI for contract B, but the second field, specifying the to address, is still the one for contract A.

**Comment by juampibermani** [comment]
@tschubotz is this related to the safe? Should a get the code from the tx builder safe app and make the fix there?

**Comment by juampibermani** [comment]
@tschubotz @Arachnid i'm not being able to replicate the bug

**Comment by Arachnid** [comment]
Here's a video demonstrating it: https://www.youtube.com/watch?v=NfWI4g69xHY

You don't actually have to submit a first transaction; it's enough to paste one address in the first textbox, wait for it to load, then paste a second; the new ABI will be loaded, but the to address will still be set to the first one.

**Comment by juampibermani** [comment]
@Arachnid could you provide me both of the contract addresses you used

**Comment by juampibermani** [comment]
@Arachnid could you provide me the contract addresses you used?

**Comment by juampibermani** [comment]
I see that this issue was already solved (by erasing the "To Address" field from the inputs. I also see that it was deployed. Is it possible that these safe apps IPFS urls are not being updated?

**Comment by mikheevm** [comment]
@juampibermani there's a QA process pending: https://github.com/gnosis/safe-react-apps/pull/132 it was never released

**Comment by katspaugh** [comment]
Should be fixed in v1.1.0. ✅
