### ISSUE TITLE
Transaction builder forgets added transactions when adding new ABI or address 

### ISSUE THREAD

**Issue by Graeme-Code** [gnosis/safe-react-apps#141]
Hi there, 

This is the issue is occurring on:

app url:
https://gnosis-safe.io/app/#/safes/0x0013CEFc104698Bb40d574E2aE6C822d5D52cff3/apps?appUrl=https://cloudflare-ipfs.com/ipfs/QmTJMCBZHX56z36aTUaL2QZ3rKTkzaq1CG3zhPSKb1Su3a

Brave version:
Release Notes V1.26.74 (June 30, 2021)

Description:

After the first transaction has been added, the front end reflects this by showing (1) in the send transactions button. Then if a new ABI or Address is interested in to the "Enter Address or ABI" field, the UI reverts to "Send transactions" without the 1. 

Please find the video attached. 

https://user-images.githubusercontent.com/7915365/124475485-0f88dc00-dda2-11eb-8aa0-1cd1a6cc7e73.mov

**Comment by tschubotz** [comment]
I tried to reproduce this. The tx queue is only cleared, when an address with no ABI available is used. (or if fetching the ABI failed). It doesn't happen when fetching the ABI succeeds always.

Hence I would not say this is a critical bug. Rather a big inconvenience and I would agree to @dasanra to treat this is `enhancement` due to the L2 work right now. At least as long no other external reports come in.

**Comment by Graeme-Code** [comment]
For reference here are the tx's I was attempting to bundle: 

The Transaction has the following steps:

RedeemUnderlying USDC from cUSDC. Contract address for cUSDC is here: https://etherscan.io/token/0x39aa39c021dfbae8fac545936693ac917d5e7563 Note I don’t believe allowances are required because cUSDC contract can spend my cUSDC. This belief is based on using the UI for compound inside of Gnosis safe and noticing that the contract interaction is only the redeem underlying function.  

Approve USDC to be spent by Curve. Now that I’ve got a bit of USDC I need to let USDC know that Curve can spend my USDC. To do this I call proxy contract controlled by USDC(https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48?a=0x0013CEFc104698Bb40d574E2aE6C822d5D52cff3#readProxyContract ) at 0xa2327a938febf5fec13bacfb16ae10ecbc4cbdcf. I should make the allowance infinite as I would have that much USDC in my account at any time, plus don't wanna make approvals every time. 

Swap on Curve. Using Curve three pool address at https://etherscan.io/address/0xbebc44782c7db0a1a60cb6fe97d0b483032ff1c7#readContract using the function “exchange”. This function takes the variables:

I - index value of coin to send, in this case it's USDC, which has index of 1

J - index value of coin to receive, in this case it's DAI, which has index of 0. 

Dx - amount of coin i been exchanged 

Min_dy - the min amount of J im willing to accept.
