### ISSUE TITLE
[WalletConnect] Handle `personal_sign`

### ISSUE THREAD

**Issue by JamesLefrere** [gnosis/safe-react-apps#145]
Related: #87 , https://github.com/walletconnect/walletconnect-docs/issues/32

I'm using an app where `personal_sign` is called to authenticate WalletConnect; only `eth_sign` is supported in the safe app UI at the moment, so it's not possible to use this app.

**Comment by rmeissner** [comment]
Extension of https://github.com/gnosis/safe-react-apps/issues/87
