### ISSUE TITLE
[Improvement] use react-app-rewired instead modifying webpackDevServer manually

### ISSUE THREAD

**Issue by krzysu** [gnosis/safe-react-apps#15]
I'm developing safe app myself and I found it very annoying to always remember to dive deep in node_modules to fix CORS issue. I found `react-app-rewired` and it solved the issue for me. I hope it will help you too. Here is my `config-overrides.js`:

https://github.com/krzysu/safe-app-idle/blob/master/config-overrides.js

**Comment by rmeissner** [comment]
you can also define a local proxy https://gist.github.com/rmeissner/b66f8350c4a6b8d077007f86a9e5187c ;) 

We should add both to our documentation

**Comment by rmeissner** [comment]
does `react-app-rewired` work well with CRA 3.x? They mentioned that they are not actively supporting CRA 2.x but was not sure.

**Comment by mikheevm** [comment]
@rmeissner we use it for `safe-react` and it works fine

**Comment by krzysu** [comment]
yes, would be cool to have it all in docs :)

**Comment by mikheevm** [comment]
Seems like this was implemented. Thanks for the tip
