### ISSUE TITLE
[TX-Builder] Bool parameters being forced to true on contract interactions

### ISSUE THREAD

**Issue by jiro-ono** [gnosis/safe-react-apps#155]
# Description

Noticed a bug with the transaction builder, where when interacting with a contract that has a bool parameter it sets it to True even though setting it as False in the input field. (Also tried setting the bool as 0 and swapped it to True as well)

## Environment

+ Browser: Chrome
+ Wallet: MetaMask
+ Safe: 0x19B3Eb3Af5D93b77a5619b047De0EED7115A19e7
+ Environment:
    + production (mainnet)

### Adding tx through transaction builder

![Screen Shot 2021-08-12 at 8 18 47 PM](https://user-images.githubusercontent.com/70732637/129300430-906cd30c-078d-496c-9543-37d8b77e6026.png)

### Preview before confirming tx

![Screen Shot 2021-08-12 at 8 18 55 PM](https://user-images.githubusercontent.com/70732637/129300478-0b94baf8-745f-4471-9e6e-e797f58623d8.png)

### Last Preview screen right before submitting tx
![Screen Shot 2021-08-12 at 8 19 04 PM](https://user-images.githubusercontent.com/70732637/129300483-f83c1060-f151-404d-9667-17e9ed0e326f.png)

**Comment by mikheevm** [comment]
The app has been updated! Thanks for you contribution

**Comment by jiro-ono** [comment]
@mikheevm Still seems to set it to True on that overwrite param for me. Do I need to do anything to update the transaction builder?

**Comment by mikheevm** [comment]
Lol, I'm sorry, I meant to close a different issue. The bug is still not fixed, unfortunately

**Comment by JagoFigueroa** [comment]
All good from my end, thank you.

Talking with Yago I think that we should create an improvement to make boolean fields like this actually boolean (a dropdown with true/false selector). creating a separate improvement about this ;)
