### ISSUE TITLE
[WalletConnect] Show message when user have connected to an Dapp that exists as a Safe App

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#167]
## Overview
We know that users continue using Dapps via wallet connect when there is a Safe App that exists. Why? 
We are not 100% sure but from observing the Defi team we know that once an Tx is done, they get used doing it in a specific way, i.e with Wallet Connect. 

Why is this a problem? 

Mainly because of wallet connect reliability. This stems from projects using the default demo bridge, which is not always up. 

## Goals
As a user of the safe wallet connect app,
when I connect to a Dapp that exists as a Safe App,
I should be informed that it exists as a Safe App,
so that I know, in case of issues, I can always use the Safe App. 

concept design - Not for production:
![image](https://user-images.githubusercontent.com/7915365/137308283-ac2e0ea3-59f2-4018-a29f-4f81ad2bcc18.png)

## Dependencies
- [ ] We need to state a method to get the list of Safe Apps. We should decide whether to add it to the SDK or do the direct call to the backend
- [ ] Many apps still use a custom version hosted on IPFS so we can't do a domain match in order to detect that the app used through wallet connect is an app that already have a proper Safe App. The solution could be to add a new value in the config service setting the root domain of the app where the custom safe app is based - create ticket for backend services team.

**Comment by liliiaorlenko** [comment]
Designs: https://www.figma.com/file/iicHRaXd0ypyttJqq2WMga/Wallet-Connect?node-id=1%3A3
