### ISSUE TITLE
Transaction Builder, check ABI availability 

### ISSUE THREAD

**Issue by Graeme-Code** [gnosis/safe-react-apps#169]
## Description

Something is strange on the transaction builder, well-used addresses like DAI and USDC will return when their addresses are entered into the tx builder, an "ABI not found" message. 

The strange thing is that this is not consistent, entering in the same contract address a few minutes later will return the function methods for the contract. 

## Steps to reproduce
For reference, please use the DAI contract: 
https://etherscan.io/address/0x6b175474e89094c44da98b954eedeac495271d0f

## Expected result
Smart contract ABI is correctly fetch from Etherscan

## Obtained result
Currently in some moments the ABI is not returned. We should check if it's related to network speed issues or missing Etherscan API key in TX Builder configuration

**Comment by yagopv** [comment]
The problem are the API rate limits

We were checking for some options to solve this like:

1) Use our gateway. `/contracts/{address}` endpoint can get the abi. We can fallback to use EtherScan if the contract cannot be found but need the API keys anyway for avoiding rate limit problems
2) Use an external service as could be https://sourcify.dev

In any case, not all the contracts can be found, for example the DAI one can be found in our gateway but not through sourcify

**Comment by yagopv** [comment]
Opened an issue in https://github.com/gnosis/safe-client-gateway/issues/700 in order to centralize this in the gateway/tx service
