### ISSUE TITLE
[TX-Builder] Gather QA resources

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#183]
## Overview
Currently is difficult to share a repository with testing resources for the transaction builder. You may need to search for different kind of smart contracts for each network or even deploy it by yourself whenever you want to test a new feature. Would be easier to have some shared repository with a bunch of smart contracts covering some of the typical test cases.

## Goals
Create a resource file with smart contract for different testing interactions in the transaction builder. We could gather resources in different chains if possible to be able to perform minimum checks whenever is necessary

## Requirements
1.- QA should get a file ready with different testing smart contract resources to be shared across the team
2.- Devs can help to improve this file

**Comment by JagoFigueroa** [comment]
Talking with @liliya-soroka we think this can be closed, I am covered in terms of the resources needed for testing and documentation is something that we can do at our own pace moving forward. Cheers!
