### ISSUE TITLE
Transaction builder - Native token descriptions per network (address to address)

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#185]
## Description
We need to change the description present for the asset amount to be transferred to another account as to match the native token of a network.

(see attached screenshots)

## Environment
 - Wallet: Any will do
 - Safe: 0x6eaD891f8a756edBf248A5546ff51E01609C0DaB (Any will do)
 - Environment: Any (volta, xDai, BSC...)

## Steps to reproduce
 1. Go to transaction builder app in Volta network (for example)
 2. Build an address to address transaction

## Expected result
If I am in volta network, I should see 'VT value --- transfer X VT to'

## Obtained result
If I am in volta network, I see 'Eth value --- transfer X eth to'

## Screenshots

![Screenshot 2021-11-09 at 10 40 02](https://user-images.githubusercontent.com/92332710/140900286-934960fc-a118-45e1-8388-a6491319ac9b.png)

![Screenshot 2021-11-09 at 10 23 18](https://user-images.githubusercontent.com/92332710/140899325-7d8741be-3f97-4704-b332-a11cc7f65b69.png)

![Screenshot 2021-11-09 at 10 30 08](https://user-images.githubusercontent.com/92332710/140899331-5ac73e78-c10d-4267-b3c7-6ab331083e77.png)

**Comment by yagopv** [comment]
Stopping the development of this task by the moment

Looking at a better way to get the native token info as exposed in https://github.com/gnosis/safe-apps-sdk/issues/254

**Comment by JagoFigueroa** [comment]
All good from my end, thank you guys ;)
