### ISSUE TITLE
[Wallet Connect] Unable to approve/reject Compound transactions

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#190]
## Description
It is not possible to approve or reject a transaction for Compund using Wallet Connect safe app.

## Environment
 - Browser: Chrome
 - Wallet: Wallet Connect
 - Safe: 0x91dB860c37E83dab0A4A005E209577E64c61EEfA (any will do)
 - Environment: production (rinkeby)

## Steps to reproduce
 1. Connect safe with Compound via Wallet Connect app (https://app.compound.finance/).
 2. Perform a withdrawal of any supplied asset
 3. Have Wallet connect app open in the safe to confirm the transaction

Note: Dai can be obtained directly from Compund. Talk to me and we can generate test data together.

## Expected result
Transaction pops up and user can choose to either approve or reject transaction.
## Obtained result
Nothing happens.
## Screenshots
<img width="1512" alt="Screenshot 2021-11-10 at 10 47 35" src="https://user-images.githubusercontent.com/92332710/141090175-2947510d-11b1-4554-862f-f4dd538fd63a.png">

**Comment by mikheevm** [comment]
<img width="2558" alt="Screenshot 2021-11-22 at 15 19 22" src="https://user-images.githubusercontent.com/16622558/142877488-65c3d9f7-9929-4468-b845-7c3b87aecce6.png">

It seems to be a problem on their side because as soon you transact, their console explores with server errors.
