### ISSUE TITLE
[Tx Builder] Don't allow to perform transactions with negative values

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#195]
## Description
We should not allow to add an address to address transaction when the {{asset}} value field is negative

## Steps to reproduce
Go to Transaction Builder app and add a new address to address transaction with negative value:
 

![Screenshot 2021-12-01 at 09 49 46](https://user-images.githubusercontent.com/92332710/144201933-96a43350-1f9e-43a1-9b7b-bb6cf4ee034e.png)

## Expected result
Frontend validation blocks the user of adding a negative transaction

## Obtained result
Transaction(s) can be added and executed.

**Comment by mikheevm** [comment]
I can't say for sure if it's a bug. From the screenshot, I think the more significant problem is that the smart contract's fallback method can include logic (e.g., Proxies), so perhaps we should provide a way to specify data when interacting with a proxy. Also, there could be cases when such empty transactions are treated in a certain way like the Safe treats such empty transactions as cancellation ones.

**Comment by JagoFigueroa** [comment]
Updated the issue to better reflect what yago has been working on. Cheers!
