### ISSUE TITLE
[WalletConnect - uniswap] Not possible to confirm an unwrapping eth transaction

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#199]
## Description
It is not possible to confirm transactions to Unwrap eth via Wallet Connect app

## Environment
 - Browser: Chrome
 - Wallet: Safe + Wallet Connect
 - Safe: 0x91dB860c37E83dab0A4A005E209577E64c61EEfA (any will do)
 - Environment: production (rinkeby)

## Steps to reproduce
 1. Connect Uniswap via WC
 2. Wrap eth via uniswap if safe has none
 3. Try to unwrap it via WC

## Expected result
Transaction should pop up on Wallet Connect app

## Obtained result

https://user-images.githubusercontent.com/92332710/142379575-24cafdae-4204-4aea-ac49-2b7b8ca01d24.mov

**Comment by mikheevm** [comment]
It would be good to also have a console log from the app because chances are 99% that the problem is on the dapp side.

**Comment by mikheevm** [comment]
This is related to a smart contract problem outlined here: https://help.gnosis-safe.io/en/articles/5249851-why-can-t-i-transfer-eth-from-a-contract-into-a-safe

Unfortunately, this is something that uniswap has to fix on their side

**Comment by JagoFigueroa** [comment]
Good to know, thank you @mikheevm ;)
