### ISSUE TITLE
[Wallet Connect] Unable to open app on incognito mode in Chrome browser

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#216]
## Environment
 - Browser: Chrome, incognito mode (Firefox incognito mode working fine)
 - Safe: 0x91dB860c37E83dab0A4A005E209577E64c61EEfA (any will do)
 - App url: https://pr213--safereactapps.review.gnosisdev.com/wallet-connect/

## Steps to reproduce
Open this link on incognito mode in chrome

`https://gnosis-safe.io/app/rin:0x91dB860c37E83dab0A4A005E209577E64c61EEfA/apps?appUrl=https://pr213--safereactapps.review.gnosisdev.com/wallet-connect/`

## Expected result
After confirming disclaimer, app opens
## Obtained result
After confirming disclaimer, app crashes
![Screenshot 2021-11-25 at 16 23 40](https://user-images.githubusercontent.com/92332710/143467521-db963bee-a60b-47ca-be37-b97aefe089b5.png)

**Comment by mikheevm** [comment]
It is expected because this mode blocks localStorage

**Comment by JagoFigueroa** [comment]
aaaaaamigo! Closing this bad boy then.

**Comment by mikheevm** [comment]
You can change this in settings to allow it in incognito mode: https://stackoverflow.com/questions/63195318/domexception-failed-to-read-the-localstorage-property-from-window-in-chrom

**Comment by JagoFigueroa** [comment]
Super good to know, thank you ;)
