### ISSUE TITLE
Fix ENS app not connecting automatically

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#222]
## Warning before starting this ticket
ENS app may have incompatibilities with new ARM chips, as some dependencies were not updated yet to support them. Ideally is better to start this ticket using a computer without ARM chips

## Description
Currently the ENS app is not working anymore. After some investigation it's clear that the cause of the malfunction could be easily solved by upgrading the Apps SDK on their App. As this is a well used App and has lots of sense as Safe App we can add the fix to their repository.

## Environment
Report on ENS repository
https://github.com/ensdomains/ens-app/issues/1332

App code is also available there.

## Steps to reproduce
 1. Load https://app.ens.domains/ as a Custom Safe app and check that is not possible to use

## Expected result
 - App automatically connect to the Safe and it's able to interact with it

## Obtained result
 - App is not connecting to the Safe

**Comment by mikheevm** [comment]
fixing it should be as easy as updating safe-apps-provider dependency

**Comment by mikheevm** [comment]
I upgraded the provider and noticed that we brought some unnecessary dependencies to the safe-apps-SDK package, It would be great if we fix it first: https://github.com/gnosis/safe-apps-sdk/pull/260

**Comment by mikheevm** [comment]
the fix is ready and being reviewed: https://github.com/ensdomains/ens-app/pull/1384/files

**Comment by JagoFigueroa** [comment]
All bueno from my end, thanks! Was able to set an ENS for one of my safes with no issues using the app ;)

**Comment by JagoFigueroa** [comment]
Can confirm that all good in prod + Mainnet as well

**Comment by mikheevm** [comment]
thanks @JagoFigueroa
