### ISSUE TITLE
[Compound] Improve Compound markets detection

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#223]
## Overview
Currently we are showing some outdated or deprecated markets in Compound safe app. Also we are not showing new markets with better yield. We should update the markets to allow users to interact with new markets and get better yields.

## Goals
- [ ] Automatically detect compound markets for example using [their graph](https://thegraph.com/hosted-service/subgraph/graphprotocol/compound-v2?query=All%20Markets)
- [ ] Avoid market duplication, deprecated markets should not be shown. Deprecated markets [can be check here](https://compound.finance/markets)

## Requirements
 - At the end of this ticket the market list should be up to date
 - Currently there is a fixed token list. This should be like this still for Rinkeby or we would break app compatibility with test chain

**Comment by yagopv** [comment]
We could use `https://api.compound.finance/api/v2/ctoken` but only works on mainnet. We can make a manual config fallback for Rinkeby
