### ISSUE TITLE
[WalletConnect] Wait for execution and return real tx hash for `eth_sendTransaction` requests

### ISSUE THREAD

**Issue by jfschwarz** [gnosis/safe-react-apps#232]
## Overview

The Safe is used in different ways:
1. As a DAO Multisig where collecting all required signatures may take hours or days.
2. As a "synchronous multisig" to enforce a second/third/... pair of eyes for approving txs, like in the case of the Gnosis treasury mgmt team.
3. As a 2-factor smart wallet where a tx will be approved instantaneously from the Safe mobile app.

When transmitting transaction to the Safe via WalletConnect, the Safe app responds with an internal tx hash, that is really quite useless to most Dapps. Failing to find a corresponding tx on chain they will show some kind of error message (in the best case) or simply break.

## Goals

At least for the cases 2) and 3) it would be preferable to wait until the tx is executed and only then respond to the transaction request with the real tx hash. This would allow to use Safe WalletConnect to interact with Dapps like with a "regular" wallet–without broken flows.

Arguably even for case 1), it's better to keep the Dapp showing a loading spinner rather than letting it run into an error.

**Comment by mikheevm** [comment]
We decided to proceed with safeTxHash on both web and mobile for foreseeing feature because dApps can do much more things with it than without hash
