### ISSUE TITLE
[WalletConnect] Use submitted `gas` parameter 

### ISSUE THREAD

**Issue by jfschwarz** [gnosis/safe-react-apps#233]
The WalletConnect Safe app does not currently seem to take into account the `gas` parameter from `eth_sendTransaction` requests.

We currently have a case in the new Zodiac Pilot app (which uses WalletConnect to a Safe) where we'd like to manually define the gas amount since the automatic gas estimation gives results that are too low. Unfortunately, this is not possible at the moment.

**Comment by mikheevm** [comment]
Do you expect it to be taken into account as a safeTxGas? Because it's impossible (as of now) for us to keep this parameter because the execution is delayed

**Comment by jfschwarz** [comment]
@mikheevm Yeah, I still don't understand well enough how the Safe manages this. The goal would be that a client can control how much gas will be made available to the internal transaction once the execution happens. So I think this would be the `safeTxGas` parameter.

In Zodiac Pilot we can work around this for now with https://github.com/gnosis/zodiac-modifier-roles/pull/11.

**Comment by mikheevm** [comment]
> @mikheevm Yeah, I still don't understand well enough how the Safe manages this. 

I can relate.

> The goal would be that a client can control how much gas will be made available to the internal transaction once the execution happens. So I think this would be the safeTxGas parameter.

In Zodiac Pilot we can work around this for now with gnosis/zodiac-modifier-roles#11.

We've discussed that internally and didn't conclude. However, the wallet's gas estimation should be enough in safes 1.3.0 because it requires the internal transaction to be successful, so pretty much the same thing you did as a workaround.
