### ISSUE TITLE
Fetch RPC provider from the SDK

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#235]
## Overview
As followup of https://github.com/gnosis/safe-apps-sdk/issues/254 we need to cleanup the manual configuration of RPC endpoints for each chain. We should get this information using the Apps SDK detecting the WebApp current network

## Goals
 - Remove chain dependency from TX-Builder and Drain Safe app

## Requirements
- [x] Create a PR in `safe-react` updating the communicator to return the complete chain configuration
- [x] Upgrade types in `safe-apps-sdk` in case is necessary
- [ ] Remove RPC endpoints from Tx-Builder and Drain Safe apps and get them from the SDK

**Comment by DaniSomoza** [comment]
Added https://github.com/gnosis/safe-apps-sdk/pull/264 PR

**Comment by DaniSomoza** [comment]
Added PR in `safe-react`:  https://github.com/gnosis/safe-react/pull/3164
