### ISSUE TITLE
Add Camera support on WalletConnect app

### ISSUE THREAD

**Issue by publu** [gnosis/safe-react-apps#257]
## Overview

Having camera support on the wallet connect app would enable us to use tablets as a separate signing device

## Goals

enable tablet users to connect through walletconnect directly instead of typing/pasting the walletconnect uri

## Requirements

![telegram-cloud-photo-size-1-5086951942919399975-y](https://user-images.githubusercontent.com/4308462/147974211-f7421dc9-f56c-4efb-b283-80ee4388c1c1.jpg)

a simple [o] button inside the typing area would be ideal

**Comment by DaniSomoza** [comment]
Hi @publu Cool idea! Thanks for sharing! I will start with this now! :D
