### ISSUE TITLE
Explore ways to add warnings or additional info to the app

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-react-apps#260]
## Overview
Context: Gnosis Market Maker app is deprecated and should no longer be used except withdrawing funds. A user deposited funds into the protocol and discovered it doesn't work anymore. To protect user funds, we need to have a way to add warnings/additional messages about such apps

## Goals
- protect user funds
- warn users about deprecated funds that are only listed for withdrawing

## Requirements
To be discussed

## Links
https://discord.com/channels/907968493134155807/908129717507461130/929254227866447902

**Comment by dasanra** [comment]
This ticket should be handled as a problem statement. I added to the list as draft and will continue prioritization from there.

We already discussed about some solutions, most probably we will need changes in the config service to attach a status/info message to the safe app and also some component to show message on top of the iframe, to be discussed with design.

We will elaborate from here
