### ISSUE TITLE
[Tx Builder] Research - Inconsistencies on Tx history when performing AtoA TXs of 0 asset value

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#264]
## Description

I have noticed some strange behaviours in the transaction history section when operating with Tx Builder to perform standard address to address transactions of 0 asset value (which we support in the app)

Take it as a research task for now as it might be a backend issue/unexpected scenario. Maybe stop allowing 0 asset value txs from our end?

## Steps to reproduce
Use the app to perform address to address transactions of 0 asset value and check the transaction history screen.

Address used for testing: https://gnosis-safe.io/app/oeth:0xeb1116466B7eB1372cD1FAf5C26134db69A94cDA/transactions/history

## Obtained result
![Screenshot 2022-01-11 at 09 10 50](https://user-images.githubusercontent.com/92332710/148905283-9d8ae2f7-ca04-408e-9525-b4d6dfd50639.png)

Nonce 14 tx: address to address tx of 0 eth. Appears as rejected when it is not the case (an edge case, might be a bit tricky to reproduce). 

Nonce 15 tx: Correct. Missing app icon (all tx do & on different chains, opening a separate issue about this).

Nonce 16 tx: address to address tx of 0 eth (like the one with nonce 14). No Tx info.

## Expected result

Nonce 14 tx: address to address tx of 0 eth. Should appear as a 'Send' Tx of 0 eth. Was never rejected.

Nonce 15 tx: Correct.

Nonce 16 tx: address to address tx of 0 eth. Should appear as a 'Send' Tx of 0 eth.

**Comment by rmeissner** [comment]
What would be the expected output? What transactions did you exactly trigger? I

**Comment by JagoFigueroa** [comment]
Updated the ticket with the expected results @rmeissner :) 

Let me align with the team first and we will get back to you as the issue might go deeper than this (was able to reproduce it on Rinkeby as well).

Cheers!

**Comment by JagoFigueroa** [comment]
Closing this ticket as I have not been able to reproduce it again.
