### ISSUE TITLE
[Compound] More detailed asset supply and distribution

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#269]
## Description
I think we can improve the feedback that is provided to users for 'Supply APY' and 'Distribution APY' fields by adding a small image referencing the token to be supplied + COMPs in case of distribution.

Compound app:
![148931507-f8d7d29f-79d4-44d8-9be9-d4b8ababe0cc](https://user-images.githubusercontent.com/92332710/149104591-1874b554-963d-4a5c-ad84-a0a7f6d4aafd.png)

Our safe app:
![148930340-46303fb0-f973-4d1c-aaa2-9d5237a83687](https://user-images.githubusercontent.com/92332710/149105633-a355caf8-376a-4886-bbc2-c3af5de8ee5d.png)

**Comment by lukasschor** [comment]
https://github.com/gnosis/safe-react-apps/issues/268#issuecomment-1011401422

**Comment by dasanra** [comment]
No more improvements will be done for Compound app
