### ISSUE TITLE
[Xdai Bridge] Mainnet safe app not working

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#275]
## Description
At the moment of opening this ticket the application available for production mainnet is not working as expected.

## Steps to reproduce
 1. Open the app from the list of available apps
 2. Click to connect wallet

## Expected result
App working as it normally would

## Obtained result
Nothing happens. Errors on console + network
<img width="1458" alt="Screenshot 2022-01-13 at 18 04 03" src="https://user-images.githubusercontent.com/92332710/149376207-f633cf56-9b6a-4928-9bac-9e09ac2b7ad9.png">

<img width="1456" alt="Screenshot 2022-01-13 at 18 04 30" src="https://user-images.githubusercontent.com/92332710/149376216-d2994d6c-f1ac-4d7c-8847-ca22d197df02.png">

**Comment by JagoFigueroa** [comment]
should we just remove this app then? I can create a separate ticket for Omnibridge :)

**Comment by dasanra** [comment]
App will be fixed in this PR https://github.com/gnosis/safe-react/pull/3340
