### ISSUE TITLE
[Balancer Exchange] Mainnet safe app not working 

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#279]
## Description
At the moment of opening this ticket the application available for production mainnet is not working as expected.

## Steps to reproduce
 1. Open the app from the list of available apps
 2. Try to perform any asset swap

## Expected result
App working as it normally would

## Obtained result
Not possible to swap any asset

https://user-images.githubusercontent.com/92332710/149506813-32c53152-9b32-4e8b-ba6f-239f0f5754b8.mov

**Comment by yagopv** [comment]
Seems to work now @JagoFigueroa 
Perhaps the fix from @dasanra ?

**Comment by JagoFigueroa** [comment]
That can perfectly be the case. Let me move this bad boy to ready for QA and do some magic. Will let you guys now ;)

**Comment by JagoFigueroa** [comment]
No luck for me after the fix of not working apps on mainnet. The app opens and I am able to select the assets from my safe but swapping just wont work:
![Screenshot 2022-01-25 at 12 12 18](https://user-images.githubusercontent.com/92332710/150966780-cfc353ad-e5f3-485f-a933-ccb3553a8e9f.png)

**Comment by JagoFigueroa** [comment]
Okay, so I was able to see the app work for the first time. The problem with it is that more often than not it will fail to do the asset conversion showing the dark bar on the screenshot of my previous message and throwing a CORS policy error after it fails:

![Screenshot 2022-02-07 at 11 38 33](https://user-images.githubusercontent.com/92332710/152772604-10597877-b876-42f4-8b1f-df4982c3ab88.png)

I don't think we can do much about this unfortunately.
