### ISSUE TITLE
[Compound] Unable to supply ETH

### ISSUE THREAD

**Issue by joshfraser** [gnosis/safe-react-apps#28]
I get the following error while trying to supply 0.2 ETH to Compound using the Compound App from this [Safe](https://gnosis-safe.io/app/#/safes/0xBBd5c7413Eeec55E932f25f7f3177db97529b40c/apps):

<img width="990" alt="Screen Shot 2020-07-13 at 8 21 10 PM" src="https://user-images.githubusercontent.com/982234/87380008-66b8ef80-c546-11ea-82d4-2478adb49df9.png">

Checking the console, it seems to be complaining about https://gnosis-safe.io/ being blocked by the CORS policy.

**Comment by lukasschor** [comment]
Opened this ticket on safe-react: https://github.com/gnosis/safe-react/issues/1114
