### ISSUE TITLE
[BUG] transaction builder on AVAX uses mainnet deployment of MultiSend not the AVAX deployment

### ISSUE THREAD

**Issue by 0xm3rlin** [gnosis/safe-react-apps#280]
## Description

On Avalanche, the transaction builder app should use the correct MultiSendCallOnly contract (https://snowtrace.io/address/0xA1dabEF33b3B82c7814B6D82A79e50F4AC44102B#code) instead of trying to use https://snowtrace.io/address/0x40A2aCCbd92BCA938b02010E17A5b8929b49130D.

## Steps to reproduce
 1. Try creating a multisend transaction on the AVAX deployment of Gnosis Safe

## Expected result

Flawless multisend

## Screenshots

<img width="599" alt="image" src="https://user-images.githubusercontent.com/83640350/149541063-a12626b7-d8fb-406b-8ff9-a6b56fc551b8.png">

**Comment by iamacook** [comment]
It seems like `safe-deployments` has the [incorrect address](https://github.com/gnosis/safe-deployments/blob/8b0950c368503000c6c741536630aff58e453a5c/src/assets/v1.3.0/multi_send_call_only.json#L29) listed.

**Comment by liliya-soroka** [comment]
The issue appears if the network was switched after the networks with other safe contracts.
Steps to reproduce:
1. Open Rinkeby
2. Open transaction builder and create multisend transaction
3. switch network in the right corner to avalanche ( or any other network where the safe contracts have different from Rinkeby addresses - see safe-deployment for details for L2 networks)
4. open transaction builder and try to create a multisend tx ( send native coints to owner account a few times )
Current result: The Multisend contract from Rinkeby is used 
The opposite situation is true : open avalanche first and switch to Rinkeby => the contract address from avalanche will be used on Rinkeby

**Comment by liliya-soroka** [comment]
Issue moved to [gnosis/safe-react #3311](https://github.com/gnosis/safe-react/issues/3311) via [**ZenHub**](https://www.zenhub.com/)
