### ISSUE TITLE
Transaction builder can't load the ABI for Uniswap

### ISSUE THREAD

**Issue by joshfraser** [gnosis/safe-react-apps#29]
Since there isn't yet an official Uniswap app, I wanted to try to supply liquidity manually using the transaction builder. I got the following error message despite their ABI being [readily available](https://unpkg.com/@uniswap/v2-periphery@1.1.0-beta.0/build/IUniswapV2Router02.json) and [verified on Etherscan](https://etherscan.io/address/0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D#readContract):

<img width="1068" alt="Screen Shot 2020-07-13 at 8 42 32 PM" src="https://user-images.githubusercontent.com/982234/87381397-784fc680-c549-11ea-8441-6f4a2e03e907.png">

**Comment by lukasschor** [comment]
Thanks. This seems to be a bug in the Transaction builder app.

If you don't necessarily require to batch transactions. You can also use the native "Contract Interaction" feature of the Safe Multisig to call the addLiquidity function. As there this bug does not exist. 

Here's more details on how to use this feature: https://help.gnosis-safe.io/en/articles/3738081-contract-interactions

**Comment by lukasschor** [comment]
@nicosampler We need to update the transaction builder app to accommodate the fact that with Solidity version 0.6.0., the `payable` and `constant` fields have been deprecated. 

Some information on this:

https://github.com/ethereum/solidity/releases/tag/v0.6.0

https://solidity.readthedocs.io/en/v0.5.17/abi-spec.html#json vs. https://solidity.readthedocs.io/en/v0.6.11/abi-spec.html#json

**Comment by cstrangedk** [comment]
@lukasschor having a similar problem with other ABIs with the TxBuilder... and the "Contract Interaction" feature also fails with the same ABIs.

**Comment by lukasschor** [comment]
Any particular contracts that fail for you? Especially related to the "Contract Interaction" feature, as there we already update to be compatible with Solidity v0.6.0.

**Comment by cstrangedk** [comment]
Just retested, apologies - contract interaction feature works fine for Solidity v0.6.0.  TxBuilder is only failing.

**Comment by nicosampler** [comment]
@lukasschor this problem should be solved with this PR https://github.com/gnosis/safe-react-apps/pull/31.
