### ISSUE TITLE
[Furucombo] Mainnet safe app not working

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#291]
## Description
At the moment of opening this ticket the application available for production mainnet is not working as expected.

## Steps to reproduce
 1. Open the app and launch it (quite weird, app should be opened directly)
 2. Try to connect safe (quite weird again as it should connect automatically being a safe app)

## Expected result
App opening directly without needing to launch it + automatic safe connection (or at least able to connect safe)

## Obtained result
Unable to connect safe to the app

![Screenshot 2022-01-19 at 12 27 29](https://user-images.githubusercontent.com/92332710/150121306-10a750b5-6e84-46f5-b477-2c851980a5e0.png)

**Comment by mikheevm** [comment]
I hid the app, will report it to the furucombo team

**Comment by mikheevm** [comment]
The app is back online with a fix. They only had to upgrade the SDK, it looks like we broke something
