### ISSUE TITLE
[Mushrooms Finance] Mainnet safe app not working

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#292]
## Description
At the moment of opening this ticket the application available for production mainnet is not working as expected.

## Steps to reproduce
Open the app from the list of available apps

## Expected result
app always loads correctly, it shouldn't be a lottery

## Obtained result

App wont load properly most of the times + refreshing it will return 429 status codes pretty consistently

![Screenshot 2022-01-19 at 12 38 59](https://user-images.githubusercontent.com/92332710/150123321-c82d4617-f34f-49e5-b9ec-21b3692d7a33.png)

**Comment by mikheevm** [comment]
it loads fine for me

**Comment by yagopv** [comment]
The 429 as [Cloudfare docs underline](https://support.cloudflare.com/hc/en-us/articles/115001635128-Configuring-Cloudflare-Rate-Limiting) means

```
Cloudflare Rate Limiting automatically identifies and mitigates excessive request rates for specific URLs or for an entire domain.  Request rates are calculated locally for individual Cloudflare data centers.  The most common uses for Rate Limiting are DDoS protection, Brute-force attack protection, and to limit access to forum searches, API calls, or resources that involve database-intensive operations at your origin. 

Once an individual IPv4 address or IPv6 /64 IP range exceeds a rule threshold, further requests to the origin web server are blocked with an HTTP 429 response that includes a Retry-After header to indicate when the client can resume sending requests.
```

So it seems a problem with the provider and the team under Mushroom Finance should address it @JagoFigueroa

**Comment by yagopv** [comment]
For me is working fine most of the times and the e2e is not detecting the failure consistently. When you receive the 429 first time then is normal that you continue receiving it as the docs said because you are blocked the time indicated under the Retry-After header

**Comment by mikheevm** [comment]
> So it seems a problem with the provider, and the team under Mushroom Finance should address it

The problem is that the provider is set on our side @yagopv

**Comment by yagopv** [comment]
mmm, I mean the cloud provider 😬, cloudfare is applying some rate limits

**Comment by mikheevm** [comment]
> mmm, I mean their cloud provider 😬, cloudfare is applying some rate limits

I get it, we set the IPFS provider on our side

**Comment by yagopv** [comment]
ooo 😱😱. Then true. We can talk in the daily about this because hadn't idea 😩

**Comment by JagoFigueroa** [comment]
closing this ticket as this is something out of our control. Was nice discussing it in the daily though!
