### ISSUE TITLE
[OpenZeppelin] Mainnet safe app not working

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#293]
## Description
At the moment of opening this ticket the application available for production mainnet is not working as expected.
(I understand that the Contract address field should at least recognise any mainnet contract)

## Steps to reproduce

1. Open the app and launch it
2. Input or copy / paste a contract address

Test contracts:

0x39aa39c021dfbae8fac545936693ac917d5e7563
0xef0881ec094552b2e128cf945ef17a6752b4ec5d

## Expected result
App working as expected (or If contracts are not supposed to work, at least provide some feedback)

## Obtained result
Infinite loader + error on console
![Screenshot 2022-01-19 at 12 57 38](https://user-images.githubusercontent.com/92332710/150126262-18c9252e-d62e-4e92-b9f7-c66b36c51aea.png)

**Comment by mikheevm** [comment]
The App was deployed on IPFS, so it looks like something is broken on our end.

**Comment by dasanra** [comment]
App will be fixed in this PR https://github.com/gnosis/safe-react/pull/3340
