### ISSUE TITLE
[Sushi] Update app icon on mainnet

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#294]
## Description
App icon fails to be displayed, I am getting a status code 404.

## Steps to reproduce
Go to the apps section.

## Obtained result
![Screenshot 2022-01-19 at 14 37 11](https://user-images.githubusercontent.com/92332710/150141488-3824e697-3ab9-495b-acdd-d655076112a0.png)

**Comment by yagopv** [comment]
`iconPath`  is missing in https://app.sushi.com/manifest.json

**Comment by JagoFigueroa** [comment]
All bueno, thank you
