### ISSUE TITLE
Improving visibility of Gnosis developed apps

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#298]
## Description

This is a ticket proposing on how we can improve the visibility of the safe-apps we develop (not to be implemented or anything, just having some fun).

A couple of ideas for this:

## 1

The same way we have these sections

![Screenshot 2022-01-19 at 16 26 01](https://user-images.githubusercontent.com/92332710/150163061-f3a2fe1d-82bf-4c05-b65e-c42f47defe0c.png)

Add one called 'Gnosis apps' which will be given a higher priority / visibility than 'All apps' which can be renamed to 'Third party apps'

## 2

Add the Gnosis logo to highlight our own apps

![Screenshot 2022-01-19 at 16 41 11](https://user-images.githubusercontent.com/92332710/150164875-ca1dd7d6-2133-472b-ad3e-a9fb591fc85a.png)

**Comment by mikheevm** [comment]
Why would they need a higher priority/visibility compared to other apps?

Graeme has looked for quite some time into sorting/categorizing the app, and it's not as easy as it seems and leads to many other questions (e.g., do we want to prioritize gnosis apps or most used ones? what do our users expect). I suggest creating a separate ticket with a broader problem statement

**Comment by JagoFigueroa** [comment]
Feel free to close this ticket, I am just having some brainstorming fun :)
