### ISSUE TITLE
Update Rep token to v2 for compound Safe-App

### ISSUE THREAD

**Issue by nicosampler** [gnosis/safe-react-apps#30]
cc @lukasschor

**Comment by tschubotz** [comment]
Are you sure that Compound supports Repv2 already? If it see it correctly, they are still using the old REP for their market https://etherscan.io/token/0x158079ee67fce2f58472a96584a73c7ab9ac95c1#readContract

**Comment by tschubotz** [comment]
closing this for now, please reopen in case I got anything wrong about the token. @lukasschor @nicosampler
