### ISSUE TITLE
[Bancor network] Mainnet safe app not working

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#311]
## Description
At the moment of opening this ticket the application available for production mainnet is not working as expected.

## Steps to reproduce
Open the app from the list of available apps

## Expected result
App loading as expected

## Obtained result
![Screenshot 2022-02-07 at 10 16 38](https://user-images.githubusercontent.com/92332710/152759497-77075bfb-b35e-43e5-973a-8ff71ef11fac.png)

**Comment by mikheevm** [comment]
reported to the team

**Comment by zavelevsky** [comment]
Hi, please try now.

**Comment by mikheevm** [comment]
fixed! thanks @zavelevsky
