### ISSUE TITLE
Use icons array in safe apps manifest instead of iconPath

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-react-apps#329]
# What is this feature about? (1 sentence)
We're using the property `iconPath` to get the app's icon. This property is our own and not included in the standard.
There's a property `icons` that is standardized and we can use: https://web.dev/add-manifest/#icons https://www.w3.org/TR/appmanifest/#json-schema
MDN uses an object but it seems outdated.

# Why is it needed? What is the value? For whom do we build it?
Currently our manifest.json logic is not the same as the common manifest.json logic for web apps (or PWAs). Therefore we cannot take advantage of the existing manifest.json files in most apps without additional changes to it. By complying to the standard it will be possible to use existing apps as Safe apps without additional migration steps (at least in many cases).

# High-level overview of the feature
It should be done in a backward-compatible way. We should use a closest image to 60x60

**Comment by yagopv** [comment]
> It should be done in a backward-compatible way. We should use a closest image to 60x60

We are currently trying to find the [best image](https://github.com/safe-global/safe-react/blob/d1a20f04f7e4c46d8edff45fb8be7580c504dfe5/src/routes/safe/components/Apps/utils.ts#L128) we can inside the icons array:

1) Trying to find a vector (svg) or something the app indicates that fonts any size (any)
2) Trying to find some image bigger than 128px
3) Fallback to whatever is present
