### ISSUE TITLE
[Compound] Asset withdrawal not working on Rinkeby

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#345]
## Description
There is an issue in the Rinkeby version of the Compound app that it is not actually withdrawing the supplied assets.

## Steps to reproduce
 1. Go to the Compound app and perform an asset withdrawal (for ETH for example).

## Expected result
Supplied assets are withdrawn.

## Obtained result
Transaction is created & executed but no asset withdrawal is being performed

**Comment by dasanra** [comment]
For me it's working as expected
