### ISSUE TITLE
[Tx Builder] Visual issues with labels

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#361]
## Description
Similar to this ticket https://github.com/gnosis/safe-react-apps/issues/360 we need to update the component library to fix some minor visual issues with labels

## Steps to reproduce
1. On Tx Builder app use this testing contract 0x49d4450977E2c95362C13D3a31a09311E0Ea26A6
2. Check the label referencing the contract methods

## Expected result
No visual issues

## Obtained result

![Screenshot 2022-03-07 at 16 31 14](https://user-images.githubusercontent.com/92332710/157064942-1d4ec4e4-7582-47ef-ad94-72ada1bde79d.png)

**Comment by yagopv** [comment]
@JagoFigueroa you can test this only in the feature/tx-builder-transaction-library branch
