### ISSUE TITLE
[TX-Builder] Design improvements

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#368]
## Overview
After Lila review we have some suggestions to improve TX-Builder designs

## Goals
Add design corrections suggested by Lila

## Requirements

- [x] 1. check the distances between text fields, it should be 24px for the error text to not mess up the structure
- [x] 2. tool tip shouldn't contain a grey border, also if we can make tool tip visible only 1-2 seconds after hovering on it, so it wouldn't be as pushy for the users who already understand the interface
- [x] 3. color for hover state on a transaction (for the drag and drop action) would be #EFFAF8
- [x] 4. at the review page at the state of open transaction please follow [the design](https://www.figma.com/file/G7snLqBXWNPANcOj5MhiR7/Transaction-Builder?node-id=832%3A9776) (no grey background)

## Screens
1. Screenshot for first requirement:
<img width="569" alt="Screenshot 2022-03-09 at 15 17 13" src="https://user-images.githubusercontent.com/25051234/157479925-22600ac2-ff6b-4941-b5c6-7cebab402612.png">

2. Screenshot for second requirement:
<img width="241" alt="Screenshot 2022-03-09 at 15 21 59" src="https://user-images.githubusercontent.com/25051234/157478900-993dc4e7-2426-4b60-96aa-4f0cd2992e40.png">

3. Screenshot for third requirement:
<img width="610" alt="Screenshot 2022-03-09 at 15 24 45" src="https://user-images.githubusercontent.com/25051234/157479792-3d5a7bd7-2dd8-46bb-8961-7816924d407e.png">

4. Screenshot for fourth requirement:
<img width="984" alt="Screenshot 2022-03-09 at 15 28 47" src="https://user-images.githubusercontent.com/25051234/157479120-e670ea70-0a3e-41bb-b775-dca20a78d150.png">

**Comment by JagoFigueroa** [comment]
All good! Thank you Dani ;)
