### ISSUE TITLE
When an user create a Safe from Safe App landing page redirect this user to Safe App

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#417]
## Overview
We allow an user to create a new Safe in the flow when showing a Safe App. If this is the case we should store that the user came from this flow and redirect back to the Safe App after completing the Safe creation flow

## Goals
If an user starts the Safe creation process from the Safe App landing, we should loop back the user to the Safe App after finishing the Safe creation

## Requirements

- An user that clicks on create Safe from Safe App details view is redirected to create Safe form
- We need to store that the user was redirected from this section
- After the Safe is created successfully, we need to loop back the user to the Safe App

## Screens
 - [Figma](https://www.figma.com/file/v56CKWh6Yp60cSsZ71URB0/dApp-sharing-functionality?node-id=1%3A111)

## Links
#414

**Comment by JagoFigueroa** [comment]
Redirection is working nicely! Only edge case that I can think of is when an app is not working as expected and the user will be redirected to this is screen instead:

![Screenshot 2022-04-18 at 13 52 46](https://user-images.githubusercontent.com/92332710/163804446-af3805ed-a45f-4a79-b549-137df57bc7e0.png)

But I feel like this is something out of our control.

Un abrazo ;)
