### ISSUE TITLE
[Tenderly simulation] Single send txs marked as successful when they will be not

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#425]
## Description

There is an edge case with the simulation implemented in https://github.com/gnosis/safe-react-apps/pull/391 when operating with non batched transactions where transactions that will fail are marked as successful.

## Steps to reproduce
Create a single send tx via transaction builder (either a fallback method one from safe to safe or a transfer tx to a EOA wallet) of an asset amount higher than the one available on the safe.

<img width="517" alt="165091769-eec4987e-6c50-47d9-9c40-eb66c71ddc5f" src="https://user-images.githubusercontent.com/92332710/165269465-fca77476-21a0-41f3-afd9-cf91e60f02e5.png">

## Expected result
Simulation marked as failed.

<img width="608" alt="165090522-3f2dd738-3449-4350-955a-08d2fcb53e93" src="https://user-images.githubusercontent.com/92332710/165269528-670d1c51-efdb-4008-a66f-f0a7865f475a.png">

## Obtained result
Simulation marked as success.

<img width="601" alt="165090207-5d07d5e8-102f-46bc-b640-986dc9e968ec" src="https://user-images.githubusercontent.com/92332710/165269572-c61aa1f3-fb78-4e58-aac4-26469b27534a.png">

**Comment by mikheevm** [comment]
what's your safe version? I cannot reproduce it. For me it fails on 1.3.0.

I think it can be related that transactions with safeTxGas 0 never really fail on 1.1.1

**Comment by mikheevm** [comment]
I also found a bug where instead of transaction value it'd pass 0 to the simulation, please re-check it in the latest deployment

**Comment by dasanra** [comment]
> I also found a bug where instead of transaction value it'd pass 0 to the simulation, please re-check it in the latest deployment

I think this was the real problem with what Jago reported

**Comment by JagoFigueroa** [comment]
yeah, I agree @dasanra . I can't reproduce the issue anymore so all bueno from my side, I think we can just close this.

Cheers!
