### ISSUE TITLE
WalletConnect Safe app: Info text is implemented wrong

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#46]
The explanation on the right of the WalletConnect Safe App seems to be implemented wrong. It should show the “How to connect to Dapp” explanation when no connection is active and the “how to confirm transactions” explanation when there is an active connection. 

![image (3).png](https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/55c85ec4-94d4-4c7f-ba26-f78bcb39e862)
![image (2).png](https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/bb2a3c88-b74f-4b76-b999-fffb51183697)

**Comment by francovenica** [comment]
They instructions were swapped. Is already in prod:
![image.png](https://images.zenhubusercontent.com/5e14b8e3edee21d6f9aa6c8a/f7f6aff5-e492-4c07-aa81-40e7352d6bdf)

![image.png](https://images.zenhubusercontent.com/5e14b8e3edee21d6f9aa6c8a/9256cacc-8d64-4740-93d6-e468ca0820c1)
