### ISSUE TITLE
[xDai] - Transaction Builder ABI lookup

### ISSUE THREAD

**Issue by fernandomg** [gnosis/safe-react-apps#53]
Parametrize the address to lookup for the ABI based on the connected network.

Currently, etherscan is hardcoded.

**Comment by nicosampler** [comment]
In order to test this ticket I have created this contract:
https://blockscout.com/poa/xdai/address/0x3001FBD7402B7d1BB88eE57aC4d0628e796fA256/contracts

the code was validated, so by entering the address, it should autocomplete all the methods.

Here is the ABI if you want to test it independently:
[
	{
		"inputs": [
			{
				"components": [
					{
						"internalType": "uint256",
						"name": "amount",
						"type": "uint256"
					},
					{
						"internalType": "string",
						"name": "name",
						"type": "string"
					}
				],
				"internalType": "struct YourContract.testStruct[]",
				"name": "values",
				"type": "tuple[]"
			}
		],
		"name": "swap",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"components": [
					{
						"internalType": "uint256",
						"name": "amount",
						"type": "uint256"
					},
					{
						"internalType": "string",
						"name": "name",
						"type": "string"
					}
				],
				"internalType": "struct YourContract.testStruct",
				"name": "values",
				"type": "tuple"
			}
		],
		"name": "swap2",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "values",
				"type": "string"
			}
		],
		"name": "swap3",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "values",
				"type": "uint256"
			}
		],
		"name": "swap4",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "counter",
		"outputs": [
			{
				"internalType": "uint8",
				"name": "",
				"type": "uint8"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]

**Comment by nicosampler** [comment]
@dasanra It will be necessary to build the safe-apps exclusively for xDai. WallectConnect does not have problems but tx-build does. The change required by the devOps it's pretty straightforward they only need to set this env var REACT_APP_WEB3_PROVIDER_URL=https://rpc.xdaichain.com/
