### ISSUE TITLE
Separate Safe apps

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-react-apps#55]
Currently all Safe apps are 1 React app. This cause issues when updating dependencies and also with meta information files. Therefore we should properly separate them so that each safe app is their own react app (they can still all exist in the same repo).

**Comment by dasanra** [comment]
The app separation can be considered done. Only CI is pending for this. Already discussed with devops on how to deal with this and they created a task to configure it for the week of 23rd Nov. Until then we can handle app deployment as we did with external apps. Will create a new task for all the steps necessary on our side.

**Comment by tschubotz** [comment]
Since this the WalletConnect app seems to use a wrong heading for me/ 
![image](https://user-images.githubusercontent.com/1380529/99513572-14bc2680-298b-11eb-8a98-b34570b828ab.png)

Is this something which is already recorded some where or should I open a bug ticket?
cc @nicosampler

**Comment by nicosampler** [comment]
I think it would be better to create a new ticket.

**Comment by tschubotz** [comment]
> I think it would be better to create a new ticket.

gnosis/safe-react-apps#76
