### ISSUE TITLE
[WalletConnect] respond to `eth_sendTransaction`

### ISSUE THREAD

**Issue by Velenir** [gnosis/safe-react-apps#62]
Currently the WalletConnect safe app doesn't send a response to `eth_sendTransaction` calls. Neither when transaction is approved wallet-side, nor when it is rejected.

This makes it impossible to await a transaction sent with `web3.eth.sendTransaction` as **web3** internally depends on transaction hash returned in response to `eth_sendTransaction`, or to know if the user rejected the transacation on the wallet side

**Comment by hellwolf** [comment]
Question, when is this going to be reflected in the public testnet deployment of the gnosis safe?

**Comment by mikheevm** [comment]
@hellwolf it should be available on dev environment in the next few days, I'm working on a CI setup because we recently migrated to monorepo. For staging/production deployments I'm not sure

**Comment by hellwolf** [comment]
Thanks @mikheevm ! Sorry for my ignorance, how could we use gnosis safe from dev environment instead?

**Comment by mikheevm** [comment]
@hellwolf https://safe-team.dev.gnosisdev.com/app/#

**Comment by kobuta23** [comment]
Hello @mikheevm still doesn't seem to work properly on our end. 
Promise remains unresolved, both in case of approved and rejected tx.

I see these errors on console on https://safe-team.dev.gnosisdev.com/app/#
TX Approved:
![image](https://user-images.githubusercontent.com/6445649/105350552-4350ba80-5be3-11eb-8e29-ec1f65442070.png)

TX Rejected:
![image](https://user-images.githubusercontent.com/6445649/105350383-fa006b00-5be2-11eb-900f-5f4643f6f0a9.png)

**Comment by devzl** [comment]
Hey @mikheevm & Gnosis team. The response to 'eth_sendTransaction' seems to return a wrong txHash.

Link used: https://safe-team.dev.gnosisdev.com/app/#
Network: Rinkeby

Example: 

Sent tx's receipt:
![image](https://user-images.githubusercontent.com/17701838/107903823-75d3a600-6f4a-11eb-992f-7ce177cc91df.png)
Etherscan link of it: https://rinkeby.etherscan.io/tx/0x6b5d378d81f6f67294a3222646474ceb3ce29af730cc80ebf17e741117067fe3
Actual tx hash when looking at the logs of the safe's address: https://rinkeby.etherscan.io/tx/0x6a1dfa751630928b3d3dd74efd478387a0a568fc65263eb237f1bd94a49de618

**Comment by mikheevm** [comment]
@devzl 

Hey, since safe is a multisig wallet, we may not have the "real" transaction hash since the beginning because the transaction could be possibly signed off-chain.

What we return is the transaction hash used internally in safe contracts: https://github.com/gnosis/safe-contracts/blob/760f6347844d848b4a2034c44e02f1e5463c4db1/contracts/GnosisSafe.sol#L403

**Comment by devzl** [comment]
Thanks for the prompt reply @mikheevm 

How would you ideally track a transaction from the moment the internal hash is generate to the moment it's successfully validated on-chain? Is there a (semi-)direct way to map that hash to a on-chain tx or do we need to figure out transactions from subscribing to logs and sent params and events data? (referencing this for the second part of my question: https://docs.walletconnect.org/smart-wallets#transactions)

**Comment by mikheevm** [comment]
There's no easy way to do that due to the nature of multi-signature wallets. You can use Safe Transaction Service `GET
​/transactions​/{safe_tx_hash}​/` endpoint to check the status of the transaction.

Swagger: https://safe-transaction.gnosis.io/
Docs: https://docs.gnosis.io/safe/docs/services_transactions/

**Comment by devzl** [comment]
Ok will check that out! 

Is there an ETA of when this fix will be deployed to production? @mikheevm

**Comment by mikheevm** [comment]
@devzl it's already deployed

**Comment by devzl** [comment]
Oh, I must've been using the old version, there are two wallet connect apps list on the Apps list on your platform:

This deployment doesn't return a txHash: `appUrl=https://ipfs.io/ipfs/QmWwSuByB3B3hLU5ita3RQgiSEDYtBr5LjjDCRGb8YqLKF`
While this one does: `appUrl=https://ipfs.io/ipfs/QmT3VxxfFtfEcvq8AeaoFAyUGxePRa2zisvnxLTrQXU5Uf`

@mikheevm

**Comment by mikheevm** [comment]
@devzl the old one must be persisted in local storage, try to clear it
