### ISSUE TITLE
[Tx Builder] Migrate to apps-portal.safe.global

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-react-apps#697]
Dependencies:
- Migrating the localStorage
- Updating the transaction service

### Local storage migration

What is stored?

- User’s batches

How to migrate?

- ~~Automatically like sausage-fork~~
- Offer manual migration via export/import

Show a warning banner with a link to the old domain and ask the user to export/import.

### Updating the transaction service

If not updated, the tx list will show no logo and “Contract interaction” instead of “Tx Builder”.

Sync with @Uxio0  to do a migration as soon as we update the config-service.

## Action points

- Create a warning banner
    - Web team will create the banner
    - Franco will test the flow
    - Set the deadline by 1 Sep, old app won’t exist after that
    - Link to a help article on how to export/import + link to the old app
    - Check analytics around 1 Sep for old app opening
- Update the CI of the tx builder to deploy to the new domain
    - move the old code to apps/tx-builder-old
    - put the new one to apps/tx-builder
    - link to [https://apps.gnosis-safe.io/tx-builder-old/](https://apps.gnosis-safe.io/tx-builder-old/) in the banner
    - the new one is https://apps-portal.safe.global/tx-builder
- Publish the new version of the app and replace it in the config service
    - Old app will be still accessible

**Comment by Uxio0** [comment]
What would be the migration required for the tx service?

**Comment by dasanra** [comment]
> 

@Uxio0 on the indexed transactions, those that have on the safeApp info the domain `apps.gnosis-safe.io` should be changed to `apps-portal.safe.global` to still show correct logo and name on the transaction list.

**Comment by Uxio0** [comment]
You mean the `origin` field needs to be migrated? Could you open an issue on https://github.com/safe-global/safe-transaction-service/issues with all the requirements so we can check?

**Comment by DaniSomoza** [comment]
In the second Action point:

- Update the CI of the tx builder to deploy to the new domain
    - move the old code to apps/tx-builder-old
    - put the new one to apps/tx-builder
    - link to [https://apps.gnosis-safe.io/tx-builder-old/](https://apps.gnosis-safe.io/tx-builder-old/) in the banner
    - the new one is https://apps-portal.safe.global/tx-builder
    
do you think that you need to duplicate the project? It seems that you should show a banner if you are in an specific domain, so you can create that banner and do something like this:
```
const showBanner = location.hostname == "https://apps-portal.safe.global/"
```

And in the JSX:
```
showBanner && <Banner />
```
