### ISSUE TITLE
Fix WalletConnect Safe app instructions

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-react-apps#72]
# Issue
In the WalletConnect Safe app we write as instructions the following
`2) Copy QR code image into clipboard (Shift+Command+4 on Mac, Windows key+PrtScn on Windows).`

However on Mac, it takes `Command+Control+Shift+4` to make a screenshot and save it to the clipboard.

# Task

Please fix the wording by writing `2) Copy QR code image into clipboard (Command+Control+Shift+4 on Mac, Windows key+PrtScn on Windows).`

**Comment by dasanra** [comment]
This issue can be tested in this PR as we already had to update the text there:

https://github.com/gnosis/safe-react-apps/pull/70

**Comment by francovenica** [comment]
Had to add the new WC ipfs URL 
https://ipfs.io/ipfs/QmVWjxqMYuqZ4WvxKdrErcTt1Sx5JHxZosjYz9zHiHRAiq/

![image.png](https://images.zenhubusercontent.com/5e14b8e3edee21d6f9aa6c8a/46480f25-e137-421f-957d-1d607eb6632b)

Looks good to me
