### ISSUE TITLE
Is there any support for Binance Smart Chain, or any plans?

### ISSUE THREAD

**Issue by b1u3h4t** [gnosis/safe-react-apps#73]
Binance Smart Chain currently does not have a de facto standard for multi-signatures. Do you consider adding it to Binance Smart Chain?

**Comment by tschubotz** [comment]
Hey, thanks for reaching out.
I'm afraid currently we don't have any plans for support Binance Smart chain. We primarily support Ethereum mainnet. We recently added support for xDai as an L2 solution and for EWC (Energy web chain) as part of a cooperation.

Adding another chain adds quite some maintenance overhead for us. So far there haven't been many users requesting support for Binance smart chain hence we currently don't see the need.
