### ISSUE TITLE
Transaction builder: Don't display events

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-react-apps#74]
### Title/Description
The events are displayed together with the functions

### Environment
 - Browser: Chrome
 - Safe: 0x1230B3d59858296A31053C1b8562Ecf89A2f888b ( any)
 - Wallet: MM
 - App Version: 2.14.1
 - Environment:
   - staging (rinkeby)

### Steps to reproduce
1. Go to Transaction builder
2. Add contract address `0xc778417e063141139fce010982780140aa0cd5ab`
3. Check functions list
Current result: There are both the functions and the events in the list
![image](https://user-images.githubusercontent.com/338622/99232115-903e9c00-2802-11eb-9481-3df612455a95.png)

### Expected result
Only functions should be displayed

**Comment by tschubotz** [comment]
@liliya-soroka thanks for reporting. I just transferred the issue to the safe-react-apps repo. All bugs/issues inside safe apps should go there :)

**Comment by fernandomg** [comment]
closed in #79
