### ISSUE TITLE
Header in WalletConnect Safe app has wrong font

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-react-apps#76]
Since the last WalletConnect Safe app update, the header font seems to be wrong.

https://user-images.githubusercontent.com/1380529/99513572-14bc2680-298b-11eb-8a98-b34570b828ab.png

I'm assigning "medium" just because we recently switched to the ipfs deployment for Safe apps and so we can check out if this is a bigger issue or not. I assume the same will happen once we move the other Safe apps to ipfs as well.

**Comment by nicosampler** [comment]
Good catch Toby, I forgot to copy the GlobalStyles in tx-builder and wallet-connect.
