### ISSUE TITLE
[WalletConnect] handle `eth_sign`

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-react-apps#87]
Safe apps currently don't have any way to generate pure off-chain signatures (that don't require a transaction) that can be validated via EIP-1271. BUT the safe has a method called `signMessage` that can be used to mark a message hash as "signed" so that when the EIP-1271 callback is called it is a valid signature.

Steps:
* the hash passed via `eth_sign` needs to be converted to bytes and a transaction that calls `signMessage` with it needs to be created (see https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L307) 
* A signature with 0 length needs to be returned to the dapp (see https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L330)
* The dapp needs to call the *old* EIP-712 validation method (`isValidSignature(bytes calldata _data, bytes calldata _signature)`)
  * For rinkeby we can write a new fallback handler that converts the new method to the old method

**Comment by mikheevm** [comment]
Should it also respond to eth_personalSign?

I'm trying to understand the difference but not really successful. Found this: https://gist.github.com/miguelmota/f75be1de350a0196db4a90cc96a5505f

**Comment by rmeissner** [comment]
I would ignore `personal_sign` for now

**Comment by chntr** [comment]
@rmeissner any help here? I am trying to sign a message with my EOA. This is what I have set up currently. 

This is with a single owner on the safe on Rinkeby
1. Opensea has a personal_sign request with string <message to sign>:
2. I translate it to a EIP712_SAFE_MESSAGE_TYPE and sign with my wallet : 
```
const hash = ethers.utils.hashMessage(<message to sign>)
const sig = await signer._signTypedData(
                {
                  verifyingContract: <safe address>,
                  chainId: <safe chain id>,
                },
                EIP712_SAFE_MESSAGE_TYPE,
                { message:  hash }
              ); 
```
3. Call to isValidSignature(hash, sig) returns the magic value 0x1626ba7e   (so that works)        
4. The signature is sent to Opensea but is never authorized. 

Any idea what opensea is using for auth check? If they do call isValidSignature are they not passing the same hash that I signed? 

Thanks!

**Comment by mikhailxyz** [comment]
> @rmeissner any help here? I am trying to sign a message with my EOA. This is what I have set up currently.
> 
> This is with a single owner on the safe on Rinkeby
> 
> 1. Opensea has a personal_sign request with string :
> 2. I translate it to a EIP712_SAFE_MESSAGE_TYPE and sign with my wallet :
> 
> ```
> const hash = ethers.utils.hashMessage(<message to sign>)
> const sig = await signer._signTypedData(
>                 {
>                   verifyingContract: <safe address>,
>                   chainId: <safe chain id>,
>                 },
>                 EIP712_SAFE_MESSAGE_TYPE,
>                 { message:  hash }
>               ); 
> ```
> 
> 3. Call to isValidSignature(hash, sig) returns the magic value 0x1626ba7e   (so that works)
> 4. The signature is sent to Opensea but is never authorized.
> 
> Any idea what opensea is using for auth check? If they do call isValidSignature are they not passing the same hash that I signed?
> 
> Thanks!

This seems to be a question for OpenSea.
