### ISSUE TITLE
Better communicate the need to stay in the WalletConnect Safe app

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-react-apps#93]
# What is this feature about? (1 sentence)

This will add more info text for the user to understand that they need to be in the WalletConnect app in order for dapp txs to show up.

# Why is it needed? What is the value? For whom do we build it?

- This is connected to our problem area "Inconvenient way to interact with standalone Dapps" on our roadmap.
- Currently, the WalletConnect app needs to be open in order for WalletConnect dapp txs to show up.
- We mention this in the wording, but it's not super apparent.
<img src="https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/5f7a1208-e8f9-4468-b022-1126dd711778" width="450">

# High-level overview of the feature

_details to tbd_

Option 1: 
- Add in bold to point 2: "**You need to have this WalletConnect Safe app open for transactions to pop up. You will not receive transaction requests when you don't have it open.**"

Option 2:
- Have a popup that the user needs to click away for the first time with the info above.

**Comment by tschubotz** [comment]
@posthnikova could you please make suggestion for this when you have time?

**Comment by posthnikova** [comment]
I was thinking about a banner like 'Don't leave the page' which we have on Safe creation. 

![image](https://user-images.githubusercontent.com/45787536/105842993-54307000-5fd7-11eb-9b01-0a89dd52edf9.png)
![image](https://user-images.githubusercontent.com/45787536/105843000-572b6080-5fd7-11eb-90b3-3a04a2796318.png)

Or maybe some inline banner or even a warning:

![image](https://user-images.githubusercontent.com/45787536/105843074-74f8c580-5fd7-11eb-8a32-27bb37d20672.png)
![image](https://user-images.githubusercontent.com/45787536/105843084-788c4c80-5fd7-11eb-8805-3e0425ffae6f.png)

Of course we can just change the text but it's not so prominent. 

![image](https://user-images.githubusercontent.com/45787536/105843118-8b068600-5fd7-11eb-8049-03e3cfc37af7.png)

Another solution could be a warning like on websites when you have unsaved changes and try to leave the page.

![image](https://user-images.githubusercontent.com/45787536/105843174-a6719100-5fd7-11eb-87e4-9cf161aa360a.png)

**Comment by rmeissner** [comment]
I think the last proposal will be hard to imement (https://stackoverflow.com/questions/49445671/how-to-trigger-beforeunload-event-from-within-an-iframe)

**Comment by tschubotz** [comment]
Thanks for the alternatives!

My personal opinion is to go with the first one since the message there is super prominent (which it should be). And it's more prominent than the other ones. 

Interesting thought with that last one. I feel it's a bit too intrusive for user who know what they are doing.

**Comment by posthnikova** [comment]
I like the first option too.   

Zeplin updated: https://zpl.io/V1XlkwJ

**Comment by rmeissner** [comment]
How would the first one look with the mendatory padding that we put in for safe apps?

**Comment by posthnikova** [comment]
@rmeissner This green rectangle will be inside the padding.
