### ISSUE TITLE
Rinkeby Compound App shows zero token balances

### ISSUE THREAD

**Issue by bh2smith** [gnosis/safe-react-apps#95]
I suspect that the compound app has hardcoded the mainnet token data in the dropdown menu so that this is unusable on rinkeby.

(Edit, Tobi): We should either disable compound on rinkeby or use the correct token addresses:

https://safe-transaction.gnosis.io/api/v1/tokens/?search=compound
https://safe-transaction.rinkeby.gnosis.io/api/v1/tokens/?search=compound

**Comment by tschubotz** [comment]
Thanks for the report!  @bh2smith 
In case this is a blocker for you, you can use https://app.compound.finance/ on Rinkeby with the Safe via WalletConnect also :)

**Comment by bh2smith** [comment]
Nah it's just something I stumbled upon yesterday while digging into something else.

**Comment by bh2smith** [comment]
I suppose this is mostly a problem because a lot of rinkeby tokens are just minted with the appropriate names and there is not "uniswap default" tokenlist on rinkeby. I myself came upon this issue when writing the safe-airdrop app and have since manually created a static list of tokens. All of these tokens are available for sale (in abundance) on mesa.eth.link (rinkeby).

https://github.com/bh2smith/safe-airdrop/blob/master/src/static/rinkebyTokens.json

I suppose, since this is also the compound app, that any token available on rinkeby compound could/should be included in this list as well.

**Comment by nicosampler** [comment]
it's working fine for me, I've been able to deposit USDC.

![image](https://user-images.githubusercontent.com/4376509/114088131-14b1ba00-988b-11eb-9f8b-bd20a3922adc.png)

**Comment by francovenica** [comment]
Checked here

I had no issues in Prod Rinkeby to see balances of all the tokens offered 
![04-13-2021_x(2271).gif](https://images.zenhubusercontent.com/5e14b8e3edee21d6f9aa6c8a/2fcabd8b-a2f0-493e-a501-dc53d40c0507)

What I had an issue with was with USDT showing an incorrect value (more 0 that it should). We could use this ticket for that
![image.png](https://images.zenhubusercontent.com/5e14b8e3edee21d6f9aa6c8a/745cd386-8334-4c54-ad40-ed0d6c1f5ba2)
![image.png](https://images.zenhubusercontent.com/5e14b8e3edee21d6f9aa6c8a/c6db7af7-4541-4df0-9261-a5703940d172)

**Comment by tschubotz** [comment]
Same, works for me now on Rinkeby.
