### ISSUE TITLE
1inch app seems to use a wrong currency

### ISSUE THREAD

**Issue by vporton** [gnosis/safe-react-apps#98]
I tried to exchange stETH for ETH but received DAI instead. This led me to a few hundred dollars lost.

I can't understand how has this happened, if I entered DAI instead of ETH. It's likely that 1inch app has a bug, otherwise it is my brain memory bug that I chose ETH.

**Comment by krboktv** [comment]
Could you send a tx hash?

**Comment by vporton** [comment]
> Could you send a tx hash?

`0x9078c86a7de52da643e12d1a9b310242593066864297030371fcd354ae52ba35`

**Comment by tschubotz** [comment]
@vporton this issue seems to be related to the 1inch Safe app. It's maintained by the 1inch at https://github.com/1inch-exchange/gnosis.1inch.exchange. I recommend reopening the issue there in order to resolve it.
